# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build tailwind webpage

on:
  push:
    branches: [next_js]
    paths: ['**.html']


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
      
    - name: Setup node
      uses: actions/setup-node@v2

    - name: Install packages
      run: npm ci

    - name: Build project
      run: |
        npm run build
    
    - name: Export static files
      run: npm run export

    - name: Create CNAME file
      run: |
        touch out/CNAME
        echo askeland.me > out/CNAME
        
    - name: Commit and pull
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git commit out -m 'CI: Built page.' || echo "No changes to commit"
        git push origin `git subtree split --prefix out master`:gh-pages --force
