# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build tailwind webpage

on:
  push:
    branches: [next_js]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
      
    - name: Setup node
      uses: actions/setup-node@v2

    - name: Install packages
      run: npm ci

    - name: Build project
      run: |
        npm run build
    
    - name: Export static files
      run: npm run export

    - name: Create CNAME file
      run: |
        touch out/CNAME
        echo askeland.me > out/CNAME
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: out
