# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GitHub pages

on:
  push:
    branches: [eleventy]
    paths:
      - '.src/**.{js,ts,jsx,tsx,html}'
      - '.src/**.{js,ts,jsx,tsx,html}'
jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repo/get files
      uses: actions/checkout@v2
      
      
    - name: Setup node
      uses: actions/setup-node@v2

    - name: Install packages
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Add .nojekyll file
      run: touch ./out/.nojekyll
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: dist
        clean: true
        clean-exclude: |
          .forestry
          CNAME
          /posts/